---
openapi: "3.0.1"
info:
  title: "Ledger"
  description: "Ledger execution API."
  contact:
    name: "Ledger"
    url: "https://example.com"
    email: "help@example.com"
  version: "1.0.0"
servers:
- url: "http://localhost:8080"
  description: "Local development environment"
- url: "https://ledger-gateway.ledger.link/ledger"
  description: "Integration environment"
- url: "https://ledger-gateway.ledger.works/ledger"
  description: "Staging environment"
security:
- API_KEY: []
  JWT_TOKEN: []
tags:
- name: "QueueAdminResource"
  description: "Controller responsible for queue health check."
- name: "AccountResource"
  description: "Controller responsible for account (write) operations."
- name: "AccountingQueuesResource"
  description: "Controller responsible for queue messages management."
- name: "MockLoginResource"
  description: "Controller responsible for mocking an authentication service."
- name: "TemplateExecutionResource"
  description: "Controller responsible for templates execution."
paths:
  /queue/health:
    get:
      tags:
      - "QueueAdminResource"
      summary: "Check the queue status."
      operationId: "health"
      responses:
        "500":
          description: "Internal server error or unhandled error"
          content:
            application/json:
              example:
                code: 500
                message: "Detailed message."
              exampleSetFlag: true
        "401":
          description: "Unauthorized - missing or invalid API KEY"
          content:
            application/json:
              example:
                code: 401
                message: "User must be authenticated to perform this action."
              exampleSetFlag: true
        "200":
          description: "OK - successful response"
          content:
            application/json:
              exampleSetFlag: false
      servers:
      - url: "https://ledger-gateway.ledger.works/ledger-admin/admin"
        description: "Staging environment"
      - url: "https://ledger-gateway.ledger.link/ledger-admin/admin"
        description: "Integration environment"
  /accounting/account/create:
    post:
      tags:
      - "AccountResource"
      summary: "Create an account."
      operationId: "create"
      requestBody:
        description: "Creation of an account. Optionally add account properties and\
          \ client details. Optionally create a corresponding test account. Optionally\
          \ request the opening of a corresponding Virtual Iban (with Monavate)."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountDTO"
              exampleSetFlag: false
            examples:
              DEFAULT:
                description: "Creation of DEFAULT Company account"
                value:
                  accountCode: "DEFAULT"
                  accountTypeCode: "Client"
                  description: "https://www.default.it/"
                valueSetFlag: true
            exampleSetFlag: false
        required: true
      responses:
        "500":
          description: "Internal server error or unhandled error"
          content:
            application/json:
              example:
                code: 500
                message: "Detailed message."
              exampleSetFlag: true
        "401":
          description: "Unauthorized - missing or invalid API KEY"
          content:
            application/json:
              example:
                code: 401
                message: "User must be authenticated to perform this action."
              exampleSetFlag: true
        "200":
          description: "OK - successful response"
          content:
            text/plain:
              exampleSetFlag: false
        "400":
          description: "Bad request"
          content:
            application/json:
              example:
                code: 400
                message: "Detailed message."
              exampleSetFlag: true
  /accounting/amqueue/{messageId}/skip:
    post:
      tags:
      - "AccountingQueuesResource"
      summary: "Skip message in the AMQ. MessageId should be passed as path param."
      operationId: "skipAMQMessage"
      parameters:
      - name: "messageId"
        in: "path"
        required: true
        schema:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
      responses:
        "200":
          description: "OK - successful response"
          content:
            application/json:
              exampleSetFlag: false
        "400":
          description: "Bad request"
          content:
            application/json:
              example:
                code: 400
                message: "Detailed message."
              exampleSetFlag: true
  /accounting/queue/skip/{messageId}/entry:
    put:
      tags:
      - "AccountingQueuesResource"
      summary: "Skip message in SQS. MessageId should be passed as path param."
      operationId: "skipMessage"
      parameters:
      - name: "messageId"
        in: "path"
        required: true
        schema:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
      responses:
        "201":
          description: "Created"
          content:
            application/json:
              exampleSetFlag: false
        "409":
          description: "Conflict"
          content:
            application/json:
              example:
                code: 409
                message: "Detailed message."
              exampleSetFlag: true
        "400":
          description: "Bad request"
          content:
            application/json:
              example:
                code: 400
                message: "Detailed message."
              exampleSetFlag: true
  /auth/change-password:
    post:
      tags:
      - "MockLoginResource"
      summary: "Simulates a successful password change."
      operationId: "changePassword"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JsonNode"
              exampleSetFlag: false
            exampleSetFlag: false
        required: true
      responses:
        "500":
          description: "Internal server error or unhandled error"
          content:
            application/json:
              example:
                code: 500
                message: "Detailed message."
              exampleSetFlag: true
        "401":
          description: "Unauthorized - missing or invalid API KEY"
          content:
            application/json:
              example:
                code: 401
                message: "User must be authenticated to perform this action."
              exampleSetFlag: true
        "200":
          description: "OK - successful response"
          content:
            text/plain:
              exampleSetFlag: false
        "400":
          description: "Bad request"
          content:
            application/json:
              example:
                code: 400
                message: "Detailed message."
              exampleSetFlag: true
  /auth/login:
    post:
      tags:
      - "MockLoginResource"
      summary: "Simulates a successful login."
      operationId: "login"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
              exampleSetFlag: false
            exampleSetFlag: false
        required: true
      responses:
        "500":
          description: "Internal server error or unhandled error"
          content:
            application/json:
              example:
                code: 500
                message: "Detailed message."
              exampleSetFlag: true
        "401":
          description: "Unauthorized - missing or invalid API KEY"
          content:
            application/json:
              example:
                code: 401
                message: "User must be authenticated to perform this action."
              exampleSetFlag: true
        "200":
          description: "OK - successful response"
          content:
            text/plain:
              exampleSetFlag: false
        "400":
          description: "Bad request"
          content:
            application/json:
              example:
                code: 400
                message: "Detailed message."
              exampleSetFlag: true
  /auth/refresh-token:
    post:
      tags:
      - "MockLoginResource"
      summary: "Simulates a successful token refresh."
      operationId: "refreshToken"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JsonNode"
              exampleSetFlag: false
            exampleSetFlag: false
        required: true
      responses:
        "500":
          description: "Internal server error or unhandled error"
          content:
            application/json:
              example:
                code: 500
                message: "Detailed message."
              exampleSetFlag: true
        "401":
          description: "Unauthorized - missing or invalid API KEY"
          content:
            application/json:
              example:
                code: 401
                message: "User must be authenticated to perform this action."
              exampleSetFlag: true
        "200":
          description: "OK - successful response"
          content:
            text/plain:
              exampleSetFlag: false
        "400":
          description: "Bad request"
          content:
            application/json:
              example:
                code: 400
                message: "Detailed message."
              exampleSetFlag: true
  /auth/revoke-token:
    post:
      tags:
      - "MockLoginResource"
      summary: "Simulates a successful token revocation."
      operationId: "revokeToken"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JsonNode"
              exampleSetFlag: false
            exampleSetFlag: false
        required: true
      responses:
        "500":
          description: "Internal server error or unhandled error"
          content:
            application/json:
              example:
                code: 500
                message: "Detailed message."
              exampleSetFlag: true
        "401":
          description: "Unauthorized - missing or invalid API KEY"
          content:
            application/json:
              example:
                code: 401
                message: "User must be authenticated to perform this action."
              exampleSetFlag: true
        "200":
          description: "OK - successful response"
          content:
            text/plain:
              exampleSetFlag: false
        "400":
          description: "Bad request"
          content:
            application/json:
              example:
                code: 400
                message: "Detailed message."
              exampleSetFlag: true
  /accounting/journals/from-template:
    post:
      tags:
      - "TemplateExecutionResource"
      summary: "Execute template. JSON should be passed as body."
      operationId: "execute"
      requestBody:
        description: "Ledger JSON message to forward to the processing queue."
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QueueMessageDTO"
              exampleSetFlag: false
            examples:
              PAYMENT_MATCH:
                description: "Match an order and a payment"
                value:
                  type: "PAYMENT_RECEIVED"
                  accountCode: "DEFAULT"
                  amount:
                    quantity: 150.0
                    currencyCode: "EUR"
                  additionalData:
                    bankAccountCode: "ItalyClients1"
                    discountAmount: 10
                    description: "Payment from DEFAULT, discount applied"
                  source: "FRONT_END_APP"
                valueSetFlag: true
              PAYMENT_RECEIVED_CORRECTION:
                description: "Posts a reverse journal of PAYMENT_RECEIVED"
                value:
                  type: "PAYMENT_RECEIVED_CORRECTION"
                  accountCode: "DEFAULT"
                  amount:
                    quantity: 150.0
                    currencyCode: "EUR"
                  additionalData:
                    bankAccountCode: "ItalyClients1"
                    discountAmount: 10
                    description: "Correction previous erroneous posting."
                  source: "FRONT_END_APP"
                valueSetFlag: true
              CLIENT_FEE_PAYOUT:
                description: "Client fee payout"
                value:
                  type: "CLIENT_FEE_PAYOUT"
                  accountCode: "DEFAULT"
                  amount:
                    quantity: 150.0
                    currencyCode: "EUR"
                  source: "FRONT_END_APP"
                valueSetFlag: true
            exampleSetFlag: false
        required: true
      responses:
        "500":
          description: "Internal server error or unhandled error"
          content:
            application/json:
              example:
                code: 500
                message: "Detailed message."
              exampleSetFlag: true
        "401":
          description: "Unauthorized - missing or invalid API KEY"
          content:
            application/json:
              example:
                code: 401
                message: "User must be authenticated to perform this action."
              exampleSetFlag: true
        "200":
          description: "OK - successful response"
          content:
            text/plain:
              exampleSetFlag: false
        "400":
          description: "Bad request"
          content:
            application/json:
              example:
                code: 400
                message: "Detailed message."
              exampleSetFlag: true
  /accounting/journals:
    post:
      tags:
      - "TemplateExecutionResource"
      summary: "Post a custom journal"
      operationId: "postJournal"
      requestBody:
        description: "Journal data"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JournalPostingDTO"
              exampleSetFlag: false
            examples:
              Journal Posting Example:
                description: "Journal Posting Example"
                value:
                  bookingDate: "2023-11-15"
                  journalLines:
                  - registerTypeCode: "BANK"
                    lineType: "DEBIT"
                    amount: 500.0
                    currencyCode: "EUR"
                  - registerTypeCode: "REVENUE"
                    lineType: "CREDIT"
                    amount: 500.0
                    currencyCode: "EUR"
                valueSetFlag: true
            exampleSetFlag: false
        required: true
      responses:
        "500":
          description: "Internal server error or unhandled error"
          content:
            application/json:
              example:
                code: 500
                message: "Detailed message."
              exampleSetFlag: true
        "401":
          description: "Unauthorized - missing or invalid API KEY"
          content:
            application/json:
              example:
                code: 401
                message: "User must be authenticated to perform this action."
              exampleSetFlag: true
        "200":
          description: "OK - successful response"
          content:
            text/plain:
              exampleSetFlag: false
        "400":
          description: "Bad request"
          content:
            application/json:
              example:
                code: 400
                message: "Detailed message."
              exampleSetFlag: true
  /accounting/journals/wa:
    post:
      tags:
      - "TemplateExecutionResource"
      summary: "Post a custom journal with optional description and/or attachments"
      operationId: "postJournalWithAttachments"
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/AuthUser"
              exampleSetFlag: false
            exampleSetFlag: false
      responses:
        "500":
          description: "Internal server error or unhandled error"
          content:
            application/json:
              example:
                code: 500
                message: "Detailed message."
              exampleSetFlag: true
        "401":
          description: "Unauthorized"
        "200":
          description: "Journal posted successfully"
        "400":
          description: "Invalid form data"
components:
  schemas:
    AccountDTO:
      required:
      - "accountCode"
      - "accountTypeCode"
      - "description"
      type: "object"
      properties:
        accountCode:
          type: "string"
          description: "Account code (alphanumeric)"
          exampleSetFlag: false
          types:
          - "string"
        accountTypeCode:
          type: "string"
          description: "Account type code"
          exampleSetFlag: false
          types:
          - "string"
          enum:
          - "Client"
          - "Company"
          - "BankAccount"
          - "Issuer"
          - "VirtualIban"
        parentAccountCode:
          type: "string"
          description: "Parent account code"
          exampleSetFlag: false
          types:
          - "string"
        parentAccountTypeCode:
          type: "string"
          description: "Parent account type code"
          exampleSetFlag: false
          types:
          - "string"
          enum:
          - "Client"
          - "Company"
          - "BankAccount"
          - "Issuer"
          - "VirtualIban"
        description:
          type: "string"
          description: "Account description"
          exampleSetFlag: false
          types:
          - "string"
        accountProperties:
          type: "array"
          description: "Account properties"
          exampleSetFlag: false
          items:
            $ref: "#/components/schemas/AccountPropertyDTO"
            exampleSetFlag: false
          types:
          - "array"
        clientDetails:
          $ref: "#/components/schemas/ClientDetailsDTO"
          exampleSetFlag: false
        testAccount:
          type: "boolean"
          description: "Is this account a test account"
          exampleSetFlag: false
          types:
          - "boolean"
        createTestAccount:
          type: "boolean"
          description: "Create also a corresponding _TEST account (only if this account\
            \ is not a test account)"
          exampleSetFlag: false
          types:
          - "boolean"
        userName:
          type: "string"
          description: "User that is creating the account"
          exampleSetFlag: false
          types:
          - "string"
      exampleSetFlag: false
    AccountPropertyDTO:
      type: "object"
      properties:
        name:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
          enum:
          - "TimeZone"
          - "ExpiryMonths"
          - "LowBalanceNotificationThresholdEUR"
          - "LowBalanceNotificationThresholdGBP"
          - "LowBalanceNotificationThresholdUSD"
          - "AccountCurrency"
          - "ScheduledReports"
          - "ExpiryMode"
          - "IsSale"
        value:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
      description: "Account properties"
      exampleSetFlag: false
    ClientDetailsDTO:
      required:
      - "cityName"
      - "contactRef"
      - "country"
      - "email"
      - "postalCode"
      - "streetAddress"
      - "telephoneNumber"
      type: "object"
      properties:
        email:
          type: "string"
          description: "Client email"
          exampleSetFlag: false
          types:
          - "string"
        streetAddress:
          type: "string"
          description: "Street address"
          exampleSetFlag: false
          types:
          - "string"
        telephoneNumber:
          type: "string"
          description: "Telephone Number"
          exampleSetFlag: false
          types:
          - "string"
        cityName:
          type: "string"
          description: "City name"
          exampleSetFlag: false
          types:
          - "string"
        country:
          type: "string"
          description: "Country"
          exampleSetFlag: false
          types:
          - "string"
        contactRef:
          type: "string"
          description: "Contact reference"
          exampleSetFlag: false
          types:
          - "string"
        postalCode:
          type: "string"
          description: "Postal code"
          exampleSetFlag: false
          types:
          - "string"
      description: "Client Account details"
      exampleSetFlag: false
    JsonNode:
      type: "object"
      description: "Additional data, exact format depends on the message type."
      exampleSetFlag: false
    LoginRequest:
      required:
      - "username"
      type: "object"
      properties:
        username:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
      exampleSetFlag: false
    AttachmentMetaDTO:
      type: "object"
      properties:
        id:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        type:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        filename:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        contentType:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        textContent:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        uri:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        sha256:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        size:
          type: "integer"
          format: "int64"
          exampleSetFlag: false
          types:
          - "integer"
      description: "Metadata regarding journal attachments."
      exampleSetFlag: false
    QueueMessageAmountDTO:
      required:
      - "currencyCode"
      - "quantity"
      type: "object"
      properties:
        quantity:
          minimum: 0
          type: "number"
          description: "Amount to be booked."
          example: 123.45
          exampleSetFlag: true
          types:
          - "number"
        currencyCode:
          minLength: 3
          type: "string"
          description: "Currency ISO code."
          example: "EUR"
          exampleSetFlag: true
          types:
          - "string"
      description: "Amount to be booked."
      exampleSetFlag: false
    QueueMessageDTO:
      required:
      - "accountCode"
      - "source"
      - "type"
      type: "object"
      properties:
        type:
          type: "string"
          description: "Message type, determine how some other fields are handled."
          exampleSetFlag: false
          types:
          - "string"
          enum:
          - "PAYMENT_RECEIVED"
          - "PAYMENT_MATCH"
          - "JOURNAL_POST"
        accountCode:
          type: "string"
          description: "Code of account, account must exist in database."
          exampleSetFlag: false
          types:
          - "string"
        amount:
          $ref: "#/components/schemas/QueueMessageAmountDTO"
          exampleSetFlag: false
        uuid:
          type: "string"
          description: "A unique identifier. Our recommended and preferred format\
            \ is UUID V4."
          exampleSetFlag: false
          types:
          - "string"
        txReference:
          type: "string"
          description: "Transaction reference"
          exampleSetFlag: false
          types:
          - "string"
        additionalData:
          $ref: "#/components/schemas/JsonNode"
          exampleSetFlag: false
        journalInfo:
          type: "array"
          description: "Metadata regarding journal attachments."
          exampleSetFlag: false
          items:
            $ref: "#/components/schemas/AttachmentMetaDTO"
            exampleSetFlag: false
          types:
          - "array"
        source:
          type: "string"
          description: "Source of message, must be FRONT_END_APP"
          exampleSetFlag: false
          types:
          - "string"
          enum:
          - "FRONT_END_APP"
      exampleSetFlag: false
    AuthUser:
      type: "object"
      properties:
        userId:
          type: "integer"
          format: "int64"
          exampleSetFlag: false
          types:
          - "integer"
        username:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        companyAccountId:
          type: "integer"
          format: "int64"
          exampleSetFlag: false
          types:
          - "integer"
        companyAccountCode:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        roles:
          uniqueItems: true
          type: "array"
          exampleSetFlag: false
          items:
            type: "string"
            exampleSetFlag: false
            types:
            - "string"
            enum:
            - "NULL"
            - "SUPER_USER"
            - "DEFAULT"
          types:
          - "array"
        tokenIssuedAt:
          type: "string"
          format: "date-time"
          exampleSetFlag: false
          types:
          - "string"
        name:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
      exampleSetFlag: false
    JournalLinePostingDTO:
      type: "object"
      properties:
        registerType:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
          enum:
          - "Payable"
          - "BankAccount"
          - "BankBalance"
          - "BankReceived"
          - "Fee"
          - "VAT_OUT"
          - "VAT_IN"
          - "Clearing"
          - "Receivable"
          - "Revenue"
          - "UnappliedCash"
        lineType:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
          enum:
          - "DEBIT"
          - "CREDIT"
        amount:
          type: "number"
          exampleSetFlag: false
          types:
          - "number"
        currency:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
          enum:
          - "EUR"
          - "GBP"
          - "USD"
      exampleSetFlag: false
    JournalPostingDTO:
      type: "object"
      properties:
        bookingDate:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        description:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        journalLines:
          type: "array"
          exampleSetFlag: false
          items:
            $ref: "#/components/schemas/JournalLinePostingDTO"
            exampleSetFlag: false
          types:
          - "array"
      exampleSetFlag: false
    BodyPart:
      type: "object"
      properties:
        contentDisposition:
          $ref: "#/components/schemas/ContentDisposition"
          exampleSetFlag: false
        entity:
          type: "object"
          exampleSetFlag: false
          types:
          - "object"
          jsonSchema:
            type: "object"
        headers:
          type: "object"
          properties:
            empty:
              type: "boolean"
              exampleSetFlag: false
              types:
              - "boolean"
          additionalProperties:
            type: "array"
            exampleSetFlag: false
            items:
              type: "string"
              exampleSetFlag: false
              types:
              - "string"
            types:
            - "array"
          exampleSetFlag: false
          types:
          - "object"
          jsonSchema:
            type: "object"
            properties:
              empty:
                type: "boolean"
        mediaType:
          $ref: "#/components/schemas/MediaType"
          exampleSetFlag: false
        messageBodyWorkers:
          $ref: "#/components/schemas/MessageBodyWorkers"
          exampleSetFlag: false
        parent:
          $ref: "#/components/schemas/MultiPart"
          exampleSetFlag: false
        providers:
          $ref: "#/components/schemas/Providers"
          exampleSetFlag: false
        parameterizedHeaders:
          type: "object"
          properties:
            empty:
              type: "boolean"
              exampleSetFlag: false
              types:
              - "boolean"
          additionalProperties:
            type: "array"
            exampleSetFlag: false
            items:
              $ref: "#/components/schemas/ParameterizedHeader"
              exampleSetFlag: false
            types:
            - "array"
          exampleSetFlag: false
          types:
          - "object"
          jsonSchema:
            type: "object"
            properties:
              empty:
                type: "boolean"
      exampleSetFlag: false
    ContentDisposition:
      type: "object"
      properties:
        type:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        parameters:
          type: "object"
          additionalProperties:
            type: "string"
            exampleSetFlag: false
            types:
            - "string"
          exampleSetFlag: false
          types:
          - "object"
          jsonSchema:
            type: "object"
        fileName:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        creationDate:
          type: "string"
          format: "date-time"
          exampleSetFlag: false
          types:
          - "string"
        modificationDate:
          type: "string"
          format: "date-time"
          exampleSetFlag: false
          types:
          - "string"
        readDate:
          type: "string"
          format: "date-time"
          exampleSetFlag: false
          types:
          - "string"
        size:
          type: "integer"
          format: "int64"
          exampleSetFlag: false
          types:
          - "integer"
      exampleSetFlag: false
    FormDataBodyPart:
      type: "object"
      properties:
        contentDisposition:
          $ref: "#/components/schemas/ContentDisposition"
          exampleSetFlag: false
        entity:
          type: "object"
          exampleSetFlag: false
          types:
          - "object"
          jsonSchema:
            type: "object"
        headers:
          type: "object"
          properties:
            empty:
              type: "boolean"
              exampleSetFlag: false
              types:
              - "boolean"
          additionalProperties:
            type: "array"
            exampleSetFlag: false
            items:
              type: "string"
              exampleSetFlag: false
              types:
              - "string"
            types:
            - "array"
          exampleSetFlag: false
          types:
          - "object"
          jsonSchema:
            type: "object"
            properties:
              empty:
                type: "boolean"
        mediaType:
          $ref: "#/components/schemas/MediaType"
          exampleSetFlag: false
        messageBodyWorkers:
          $ref: "#/components/schemas/MessageBodyWorkers"
          exampleSetFlag: false
        parent:
          $ref: "#/components/schemas/MultiPart"
          exampleSetFlag: false
        providers:
          $ref: "#/components/schemas/Providers"
          exampleSetFlag: false
        name:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        value:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        simple:
          type: "boolean"
          exampleSetFlag: false
          types:
          - "boolean"
        formDataContentDisposition:
          $ref: "#/components/schemas/FormDataContentDisposition"
          exampleSetFlag: false
        parameterizedHeaders:
          type: "object"
          properties:
            empty:
              type: "boolean"
              exampleSetFlag: false
              types:
              - "boolean"
          additionalProperties:
            type: "array"
            exampleSetFlag: false
            items:
              $ref: "#/components/schemas/ParameterizedHeader"
              exampleSetFlag: false
            types:
            - "array"
          exampleSetFlag: false
          types:
          - "object"
          jsonSchema:
            type: "object"
            properties:
              empty:
                type: "boolean"
      exampleSetFlag: false
    FormDataContentDisposition:
      type: "object"
      properties:
        type:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        parameters:
          type: "object"
          additionalProperties:
            type: "string"
            exampleSetFlag: false
            types:
            - "string"
          exampleSetFlag: false
          types:
          - "object"
          jsonSchema:
            type: "object"
        fileName:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        creationDate:
          type: "string"
          format: "date-time"
          exampleSetFlag: false
          types:
          - "string"
        modificationDate:
          type: "string"
          format: "date-time"
          exampleSetFlag: false
          types:
          - "string"
        readDate:
          type: "string"
          format: "date-time"
          exampleSetFlag: false
          types:
          - "string"
        size:
          type: "integer"
          format: "int64"
          exampleSetFlag: false
          types:
          - "integer"
        name:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
      exampleSetFlag: false
    MediaType:
      type: "object"
      properties:
        type:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        subtype:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        parameters:
          type: "object"
          additionalProperties:
            type: "string"
            exampleSetFlag: false
            types:
            - "string"
          exampleSetFlag: false
          types:
          - "object"
          jsonSchema:
            type: "object"
        wildcardType:
          type: "boolean"
          exampleSetFlag: false
          types:
          - "boolean"
        wildcardSubtype:
          type: "boolean"
          exampleSetFlag: false
          types:
          - "boolean"
      exampleSetFlag: false
    MessageBodyWorkers:
      type: "object"
      exampleSetFlag: false
    MultiPart:
      type: "object"
      properties:
        contentDisposition:
          $ref: "#/components/schemas/ContentDisposition"
          exampleSetFlag: false
        entity:
          type: "object"
          exampleSetFlag: false
          types:
          - "object"
          jsonSchema:
            type: "object"
        headers:
          type: "object"
          properties:
            empty:
              type: "boolean"
              exampleSetFlag: false
              types:
              - "boolean"
          additionalProperties:
            type: "array"
            exampleSetFlag: false
            items:
              type: "string"
              exampleSetFlag: false
              types:
              - "string"
            types:
            - "array"
          exampleSetFlag: false
          types:
          - "object"
          jsonSchema:
            type: "object"
            properties:
              empty:
                type: "boolean"
        mediaType:
          $ref: "#/components/schemas/MediaType"
          exampleSetFlag: false
        messageBodyWorkers:
          $ref: "#/components/schemas/MessageBodyWorkers"
          exampleSetFlag: false
        parent:
          $ref: "#/components/schemas/MultiPart"
          exampleSetFlag: false
        providers:
          $ref: "#/components/schemas/Providers"
          exampleSetFlag: false
        bodyParts:
          type: "array"
          exampleSetFlag: false
          items:
            $ref: "#/components/schemas/BodyPart"
            exampleSetFlag: false
          types:
          - "array"
        parameterizedHeaders:
          type: "object"
          properties:
            empty:
              type: "boolean"
              exampleSetFlag: false
              types:
              - "boolean"
          additionalProperties:
            type: "array"
            exampleSetFlag: false
            items:
              $ref: "#/components/schemas/ParameterizedHeader"
              exampleSetFlag: false
            types:
            - "array"
          exampleSetFlag: false
          types:
          - "object"
          jsonSchema:
            type: "object"
            properties:
              empty:
                type: "boolean"
      exampleSetFlag: false
    MultivaluedMapStringParameterizedHeader:
      type: "object"
      properties:
        empty:
          type: "boolean"
          exampleSetFlag: false
          types:
          - "boolean"
      additionalProperties:
        type: "array"
        exampleSetFlag: false
        items:
          $ref: "#/components/schemas/ParameterizedHeader"
          exampleSetFlag: false
        types:
        - "array"
      exampleSetFlag: false
      types:
      - "object"
    MultivaluedMapStringString:
      type: "object"
      properties:
        empty:
          type: "boolean"
          exampleSetFlag: false
          types:
          - "boolean"
      additionalProperties:
        type: "array"
        exampleSetFlag: false
        items:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        types:
        - "array"
      exampleSetFlag: false
      types:
      - "object"
    ParameterizedHeader:
      type: "object"
      properties:
        value:
          type: "string"
          exampleSetFlag: false
          types:
          - "string"
        parameters:
          type: "object"
          additionalProperties:
            type: "string"
            exampleSetFlag: false
            types:
            - "string"
          exampleSetFlag: false
          types:
          - "object"
          jsonSchema:
            type: "object"
      exampleSetFlag: false
    Providers:
      type: "object"
      exampleSetFlag: false
  securitySchemes:
    API_KEY:
      type: "APIKEY"
      name: "X-API-KEY"
      in: "HEADER"
    JWT_TOKEN:
      type: "APIKEY"
      name: "Authorization"
      in: "HEADER"
